server:
  build: .
  links:
    - mongodb:mongodb
  ports:
    - "8080:8080"
  environment:
    MONGO_HOST: mongodb
    WEB_HOST: http://192.168.99.100
mongodb:
  image: mongo
  expose:
    - "27017"
  ports:
    - "27017:27017"
